name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker rmi my-node-app || true
            cd ~/my-app
            git pull origin main
            docker build -t my-node-app .
            docker run -d -p 80:3000 my-node-app
